/** \file
 *  This C source file was generated by $ANTLR version null
 *
 *     -  From the grammar source file : D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g
 *     -                            On : 2013-11-29 13:09:48
 *     -           for the tree parser : GeoGenScriptDeclsTreeParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "GeoGenScriptDecls.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pGeoGenScriptDecls_##scope##_SCOPE
#define SCOPE_STACK(scope)  pGeoGenScriptDecls_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pGeoGenScriptDecls_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pGeoGenScriptDecls_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef	    BACKTRACKING
#undef      ADAPTOR
#undef	    RULEMEMO
#undef		SEEK
#undef		INDEX
#undef		DBG

#define	    PARSER							ctx->pTreeParser
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    INPUT							PARSER->ctnstream
#define		ISTREAM							INPUT->tnstream->istream
#define	    STRSTREAM						INPUT->tnstream
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							ISTREAM->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->tnstream->_LT(INPUT->tnstream, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         INPUT->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define		INDEX()							ISTREAM->index(ISTREAM)
#define		DBG								RECOGNIZER->debugger



#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   GeoGenScriptDeclsTokenNames[80+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "AS",
        (pANTLR3_UINT8) "AT",
        (pANTLR3_UINT8) "BLOCK",
        (pANTLR3_UINT8) "BREAK",
        (pANTLR3_UINT8) "CASE",
        (pANTLR3_UINT8) "COLLECTION",
        (pANTLR3_UINT8) "COLON",
        (pANTLR3_UINT8) "COMMA",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "CONTINUE",
        (pANTLR3_UINT8) "COORDINATE",
        (pANTLR3_UINT8) "DECLARATIONS",
        (pANTLR3_UINT8) "DEFAULT",
        (pANTLR3_UINT8) "ELSE",
        (pANTLR3_UINT8) "ENUM",
        (pANTLR3_UINT8) "ESC_SEQ",
        (pANTLR3_UINT8) "FALSE_LIT",
        (pANTLR3_UINT8) "FOR",
        (pANTLR3_UINT8) "FUNCTION",
        (pANTLR3_UINT8) "HEX_DIGIT",
        (pANTLR3_UINT8) "IDENTCHAIN",
        (pANTLR3_UINT8) "IDENTIFIER",
        (pANTLR3_UINT8) "IF",
        (pANTLR3_UINT8) "INTEGER",
        (pANTLR3_UINT8) "LEFT_BRACKET",
        (pANTLR3_UINT8) "LEFT_CURLY_BRACKET",
        (pANTLR3_UINT8) "LEFT_SQUARE_BRACKET",
        (pANTLR3_UINT8) "METADATA",
        (pANTLR3_UINT8) "NUMBER",
        (pANTLR3_UINT8) "OPERATOR_ASSIGN",
        (pANTLR3_UINT8) "OPERATOR_ASSIGN_AND",
        (pANTLR3_UINT8) "OPERATOR_ASSIGN_DIVIDE",
        (pANTLR3_UINT8) "OPERATOR_ASSIGN_LSHIFT",
        (pANTLR3_UINT8) "OPERATOR_ASSIGN_MINUS",
        (pANTLR3_UINT8) "OPERATOR_ASSIGN_MODULO",
        (pANTLR3_UINT8) "OPERATOR_ASSIGN_OR",
        (pANTLR3_UINT8) "OPERATOR_ASSIGN_PLUS",
        (pANTLR3_UINT8) "OPERATOR_ASSIGN_RSHIFT",
        (pANTLR3_UINT8) "OPERATOR_ASSIGN_TIMES",
        (pANTLR3_UINT8) "OPERATOR_ASSIGN_XOR",
        (pANTLR3_UINT8) "OPERATOR_BIT_AND",
        (pANTLR3_UINT8) "OPERATOR_BIT_OR",
        (pANTLR3_UINT8) "OPERATOR_BIT_XOR",
        (pANTLR3_UINT8) "OPERATOR_CALL",
        (pANTLR3_UINT8) "OPERATOR_DECREMENT",
        (pANTLR3_UINT8) "OPERATOR_DIVIDE",
        (pANTLR3_UINT8) "OPERATOR_DOT",
        (pANTLR3_UINT8) "OPERATOR_EQUAL_TO",
        (pANTLR3_UINT8) "OPERATOR_EXPR_IF",
        (pANTLR3_UINT8) "OPERATOR_GREATER_THAN",
        (pANTLR3_UINT8) "OPERATOR_GREATER_THAN_OR_EQUAL_TO",
        (pANTLR3_UINT8) "OPERATOR_INCREMENT",
        (pANTLR3_UINT8) "OPERATOR_IS",
        (pANTLR3_UINT8) "OPERATOR_LESS_THAN",
        (pANTLR3_UINT8) "OPERATOR_LESS_THAN_OR_EQUAL_TO",
        (pANTLR3_UINT8) "OPERATOR_LSHIFT",
        (pANTLR3_UINT8) "OPERATOR_MINUS",
        (pANTLR3_UINT8) "OPERATOR_MODULO",
        (pANTLR3_UINT8) "OPERATOR_NOT",
        (pANTLR3_UINT8) "OPERATOR_NOT_EQUAL_TO",
        (pANTLR3_UINT8) "OPERATOR_PLUS",
        (pANTLR3_UINT8) "OPERATOR_REL_AND",
        (pANTLR3_UINT8) "OPERATOR_REL_OR",
        (pANTLR3_UINT8) "OPERATOR_RSHIFT",
        (pANTLR3_UINT8) "OPERATOR_SUBSCRIPT",
        (pANTLR3_UINT8) "OPERATOR_TIMES",
        (pANTLR3_UINT8) "PARAMETERS",
        (pANTLR3_UINT8) "RETURN",
        (pANTLR3_UINT8) "RIGHT_BRACKET",
        (pANTLR3_UINT8) "RIGHT_SQUARE_BRACKET",
        (pANTLR3_UINT8) "RIGTH_CURLY_BRACKET",
        (pANTLR3_UINT8) "SCRIPT",
        (pANTLR3_UINT8) "SEMICOLON",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "SWITCH",
        (pANTLR3_UINT8) "TRUE_LIT",
        (pANTLR3_UINT8) "VAR",
        (pANTLR3_UINT8) "WHILE",
        (pANTLR3_UINT8) "WHITESPACE",
        (pANTLR3_UINT8) "YIELD"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	enumDecl    (pGeoGenScriptDecls ctx);
static 
 void
	enumValue    (pGeoGenScriptDecls ctx);
static 
 void
	expression    (pGeoGenScriptDecls ctx);
static void	GeoGenScriptDeclsFree(pGeoGenScriptDecls ctx);
static void     GeoGenScriptDeclsReset (pGeoGenScriptDecls ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new GeoGenScriptDecls parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pGeoGenScriptDecls
GeoGenScriptDeclsNew   (pANTLR3_COMMON_TREE_NODE_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return GeoGenScriptDeclsNewSSD(instream, NULL);
}

/** \brief Create a new GeoGenScriptDecls parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pGeoGenScriptDecls
GeoGenScriptDeclsNewSSD   (pANTLR3_COMMON_TREE_NODE_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pGeoGenScriptDecls ctx;	    /* Context structure we will build and return   */

    ctx	= (pGeoGenScriptDecls) ANTLR3_CALLOC(1, sizeof(GeoGenScriptDecls));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in GeoGenScriptDecls.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base Tree parser/recognizer, using the supplied tree node stream
     */
    ctx->pTreeParser		= antlr3TreeParserNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Install the implementation of our GeoGenScriptDecls interface
     */
    ctx->enumDecl	= enumDecl;
    ctx->enumValue	= enumValue;
    ctx->expression	= expression;
    ctx->free			= GeoGenScriptDeclsFree;
    ctx->reset			= GeoGenScriptDeclsReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */

    /* Install the token table
     */
    PSRSTATE->tokenNames   = GeoGenScriptDeclsTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
GeoGenScriptDeclsReset (pGeoGenScriptDecls ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 GeoGenScriptDeclsFree(pGeoGenScriptDecls ctx)
 {
    /* Free any scope memory
     */

	// Free this parser
	//
    ctx->pTreeParser->free(ctx->pTreeParser);

    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
tree parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return GeoGenScriptDeclsTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ENUM_in_enumDecl61  */
static	ANTLR3_BITWORD FOLLOW_ENUM_in_enumDecl61_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_ENUM_in_enumDecl61	= { FOLLOW_ENUM_in_enumDecl61_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_enumValue_in_enumDecl63  */
static	ANTLR3_BITWORD FOLLOW_enumValue_in_enumDecl63_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002000008) };
static  ANTLR3_BITSET_LIST FOLLOW_enumValue_in_enumDecl63	= { FOLLOW_enumValue_in_enumDecl63_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_enumValue73  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_enumValue73_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_enumValue73	= { FOLLOW_IDENTIFIER_in_enumValue73_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expression_in_enumValue75  */
static	ANTLR3_BITWORD FOLLOW_expression_in_enumValue75_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expression_in_enumValue75	= { FOLLOW_expression_in_enumValue75_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_IDENTIFIER_in_expression85  */
static	ANTLR3_BITWORD FOLLOW_IDENTIFIER_in_expression85_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_IDENTIFIER_in_expression85	= { FOLLOW_IDENTIFIER_in_expression85_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start enumDecl
 * D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g:20:1: enumDecl : ^( ENUM ( enumValue )* ) ;
 */
static void
enumDecl(pGeoGenScriptDecls ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g:20:9: ( ^( ENUM ( enumValue )* ) )
        // D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g:20:11: ^( ENUM ( enumValue )* )
        {
             MATCHT(ENUM, &FOLLOW_ENUM_in_enumDecl61);
            if  (HASEXCEPTION())
            {
                goto ruleenumDeclEx;
            }


            if ( LA(1)==ANTLR3_TOKEN_DOWN ) {
                MATCHT(ANTLR3_TOKEN_DOWN, NULL);
                if  (HASEXCEPTION())
                {
                    goto ruleenumDeclEx;
                }

                // D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g:20:18: ( enumValue )*

                for (;;)
                {
                    int alt1=2;
                    switch ( LA(1) )
                    {
                    case IDENTIFIER:
                    	{
                    		alt1=1;
                    	}
                        break;

                    }

                    switch (alt1)
                    {
                	case 1:
                	    // D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g:20:18: enumValue
                	    {
                	        FOLLOWPUSH(FOLLOW_enumValue_in_enumDecl63);
                	        enumValue(ctx);

                	        FOLLOWPOP();
                	        if  (HASEXCEPTION())
                	        {
                	            goto ruleenumDeclEx;
                	        }


                	    }
                	    break;

                	default:
                	    goto loop1;	/* break out of the loop */
                	    break;
                    }
                }
                loop1: ; /* Jump out to here if this rule does not match */


                MATCHT(ANTLR3_TOKEN_UP, NULL);
                if  (HASEXCEPTION())
                {
                    goto ruleenumDeclEx;
                }

            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleenumDeclEx; /* Prevent compiler warnings */
    ruleenumDeclEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end enumDecl */

/**
 * $ANTLR start enumValue
 * D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g:22:1: enumValue : ^( IDENTIFIER expression ) ;
 */
static void
enumValue(pGeoGenScriptDecls ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g:22:10: ( ^( IDENTIFIER expression ) )
        // D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g:22:12: ^( IDENTIFIER expression )
        {
             MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_enumValue73);
            if  (HASEXCEPTION())
            {
                goto ruleenumValueEx;
            }


            MATCHT(ANTLR3_TOKEN_DOWN, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleenumValueEx;
            }

            FOLLOWPUSH(FOLLOW_expression_in_enumValue75);
            expression(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleenumValueEx;
            }


            MATCHT(ANTLR3_TOKEN_UP, NULL);
            if  (HASEXCEPTION())
            {
                goto ruleenumValueEx;
            }



        }

    }

    // This is where rules clean up and exit
    //
    goto ruleenumValueEx; /* Prevent compiler warnings */
    ruleenumValueEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end enumValue */

/**
 * $ANTLR start expression
 * D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g:24:1: expression : IDENTIFIER ;
 */
static void
expression(pGeoGenScriptDecls ctx)
{
    /* Initialize rule variables
     */

    {
        // D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g:25:2: ( IDENTIFIER )
        // D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g:25:4: IDENTIFIER
        {
             MATCHT(IDENTIFIER, &FOLLOW_IDENTIFIER_in_expression85);
            if  (HASEXCEPTION())
            {
                goto ruleexpressionEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexpressionEx; /* Prevent compiler warnings */
    ruleexpressionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end expression */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
