/** \file
 *  This C header file was generated by $ANTLR version null
 *
 *     -  From the grammar source file : D:\\Users\\Matej\\Desktop\\GeoGen GGS\\src\\GeoGen\\Grammar\\GeoGenScriptDecls.g
 *     -                            On : 2013-11-29 13:09:48
 *     -           for the tree parser : GeoGenScriptDeclsTreeParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The tree parser 
GeoGenScriptDecls

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pGeoGenScriptDecls, which is returned from a call to GeoGenScriptDeclsNew().
 *
 * The methods in pGeoGenScriptDecls are  as follows:
 *
 *  - 
 void
      pGeoGenScriptDecls->enumDecl(pGeoGenScriptDecls)
 *  - 
 void
      pGeoGenScriptDecls->enumValue(pGeoGenScriptDecls)
 *  - 
 void
      pGeoGenScriptDecls->expression(pGeoGenScriptDecls)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_GeoGenScriptDecls_H
#define _GeoGenScriptDecls_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct GeoGenScriptDecls_Ctx_struct GeoGenScriptDecls, * pGeoGenScriptDecls;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
GeoGenScriptDecls

 */
struct GeoGenScriptDecls_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_TREE_PARSER	    pTreeParser;


     void
     (*enumDecl)	(struct GeoGenScriptDecls_Ctx_struct * ctx);

     void
     (*enumValue)	(struct GeoGenScriptDecls_Ctx_struct * ctx);

     void
     (*expression)	(struct GeoGenScriptDecls_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct GeoGenScriptDecls_Ctx_struct * ctx);
    void	    (*free)   (struct GeoGenScriptDecls_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pGeoGenScriptDecls GeoGenScriptDeclsNew         (
pANTLR3_COMMON_TREE_NODE_STREAM
 instream);
ANTLR3_API pGeoGenScriptDecls GeoGenScriptDeclsNewSSD      (
pANTLR3_COMMON_TREE_NODE_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
tree parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define AS      4
#define AT      5
#define BLOCK      6
#define BREAK      7
#define CASE      8
#define COLLECTION      9
#define COLON      10
#define COMMA      11
#define COMMENT      12
#define CONTINUE      13
#define COORDINATE      14
#define DECLARATIONS      15
#define DEFAULT      16
#define ELSE      17
#define ENUM      18
#define ESC_SEQ      19
#define FALSE_LIT      20
#define FOR      21
#define FUNCTION      22
#define HEX_DIGIT      23
#define IDENTCHAIN      24
#define IDENTIFIER      25
#define IF      26
#define INTEGER      27
#define LEFT_BRACKET      28
#define LEFT_CURLY_BRACKET      29
#define LEFT_SQUARE_BRACKET      30
#define METADATA      31
#define NUMBER      32
#define OPERATOR_ASSIGN      33
#define OPERATOR_ASSIGN_AND      34
#define OPERATOR_ASSIGN_DIVIDE      35
#define OPERATOR_ASSIGN_LSHIFT      36
#define OPERATOR_ASSIGN_MINUS      37
#define OPERATOR_ASSIGN_MODULO      38
#define OPERATOR_ASSIGN_OR      39
#define OPERATOR_ASSIGN_PLUS      40
#define OPERATOR_ASSIGN_RSHIFT      41
#define OPERATOR_ASSIGN_TIMES      42
#define OPERATOR_ASSIGN_XOR      43
#define OPERATOR_BIT_AND      44
#define OPERATOR_BIT_OR      45
#define OPERATOR_BIT_XOR      46
#define OPERATOR_CALL      47
#define OPERATOR_DECREMENT      48
#define OPERATOR_DIVIDE      49
#define OPERATOR_DOT      50
#define OPERATOR_EQUAL_TO      51
#define OPERATOR_EXPR_IF      52
#define OPERATOR_GREATER_THAN      53
#define OPERATOR_GREATER_THAN_OR_EQUAL_TO      54
#define OPERATOR_INCREMENT      55
#define OPERATOR_IS      56
#define OPERATOR_LESS_THAN      57
#define OPERATOR_LESS_THAN_OR_EQUAL_TO      58
#define OPERATOR_LSHIFT      59
#define OPERATOR_MINUS      60
#define OPERATOR_MODULO      61
#define OPERATOR_NOT      62
#define OPERATOR_NOT_EQUAL_TO      63
#define OPERATOR_PLUS      64
#define OPERATOR_REL_AND      65
#define OPERATOR_REL_OR      66
#define OPERATOR_RSHIFT      67
#define OPERATOR_SUBSCRIPT      68
#define OPERATOR_TIMES      69
#define PARAMETERS      70
#define RETURN      71
#define RIGHT_BRACKET      72
#define RIGHT_SQUARE_BRACKET      73
#define RIGTH_CURLY_BRACKET      74
#define SCRIPT      75
#define SEMICOLON      76
#define STRING      77
#define SWITCH      78
#define TRUE_LIT      79
#define VAR      80
#define WHILE      81
#define WHITESPACE      82
#define YIELD      83
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for GeoGenScriptDecls
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
