/// @mainpage Getting started
/// 
/// This is a full reference of GeoGen Script and its standard library. <br />
/// 
/// GeoGen Script is the language used to write map scripts for GeoGen. It is high level dynamically typed procedural programming language.
/// 
/// The language's syntax is inspired by modern programming languages such as C# and Java, but its function is more similar to PHP and JavaScript. However, GGS is much simpler language than either of these, because it forgoes more advanced features such as custom classes and inheritance.
/// 
/// **How to get started?** You can use following resources:
/// - @link tutorials Tutorials@endlink explain how to write your first map script and how to use the stand alone generator.
/// - @link language_reference Language reference@endlink describes the programming language in detail.
/// - @link standard_library Standard library reference@endlink lists all classes and functions available to the scripts.    
/// - @link examples_page Example scripts@endlink demonstrate various approaches to script writing.  
/// - @link error_codes Error code reference@endlink contains information about each error code generated by GeoGen.
